### PR TITLE
Fix auditor features in forms

### LINKED ISSUE #1761: Store auditor links in drive for Forms
### Description

Storing auditor links in drive/team drive does not work as intended. It only stores a “read only” file, meaning a link to the answer form.

The only way to store an auditor link is to save the URL.

### Steps to reproduce

1. Create a form
2. Click on Share > Auditor radio button > One of your contact
3. The contact opens the auditor link and can see the form results
4. The contact clicks on “File > Store in CryptDrive” to save the link in their drive
5. Later on, the contact wants to audit the form, thus opens the stored form in their drive
6. The contact gets redirected on the answer form. Contextual menu does not allow for opening the audit page.

Alternatively:
2. Click on Share > Auditor radio button > One of your team
3. Open the newly created form in your team.
4. You get redirected on the answer form. Contextual menu does not allow for opening the audit page.

### Relevant logs

```shell

```

### Expected behavior

There should be a way to store the auditor link natively in the drive without having to store it as a link.

### Which operating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox, Google Chrome

### Extensions

Not relevant

### Version

2024.12.0

### LINKED ISSUE #1924: Form password doesn't work when sharing document in 'Auditor' mode
### Description

User not prompted to enter password when opening a password-protected form document in 'Auditor' mode

### Steps to reproduce

1. Create a form document as a logged-in user
2. Set password during creation
3. Share the document via link in 'Auditor' mode
4. When another user opens the link, they can view the document without being prompted to enter the password 

### Relevant logs

```shell
n/a
```

### Expected behavior

When the link is opened, the user should be prompted to enter the password as is the case with 'Author' and 'Participant' mode

### Which operating system are you using?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Extensions

n/a

### Version

2025.3.0

### LINKED ISSUE #1967: Sharing a participant link from auditor link on a Form does not work
### Description

Sharing an answer link from an “auditor link” view leads to a “view-only” form.

### Steps to reproduce

1. Create a form
2. Share > Link > Auditor > Open link
3. From the new tab: Share > Link > Participant > Open link
4. From the new tab: fill the form and click on “Submit”
5. Notice the error notification on the bottom left of the screen.

### Relevant logs

```shell
FAILED_VALIDATION inner.js:3605:29
    send https://cryptpad.fr/form/inner.js?ver=2025.3.1-12:3605
    txid https://cryptpad.fr/common/outer/worker-channel.js?ver=2025.3.1-12:66
    create https://cryptpad.fr/common/outer/worker-channel.js?ver=2025.3.1-12:207
    fire https://cryptpad.fr/common/common-util.js?ver=2025.3.1-12:121
    fire https://cryptpad.fr/common/common-util.js?ver=2025.3.1-12:121
    create https://cryptpad.fr/common/sframe-common.js?ver=2025.3.1-12:801
```

### Expected behavior

Participant link should not be derivable from the information stored in an auditor link (there is a signing key missing according to the [whitepaper](https://blog.cryptpad.org/images/whitepaper.pdf)).

The participant link should be disabled from the share modal from an auditor link.

### Which operating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

Not relevant

### Version

2025.3.1

### PR DESCRIPTION
**Pull request by zuzanna-maria**
- Can open Forms in Auditor mode from Drive (fixes #1761 )
- Passwords work for Forms shared in Auditor mode (fixes #1924)
- Can no longer open Participant link from Auditor link (fixes #1967)

### CODE REVIEW

File: www/common/drive-ui.js [hunk 1]
```diff
@@ -1250,7 +1250,7 @@ define([
             var secret = Hash.getSecrets(parsed.type, parsed.hash, data.password);
             var opts = {};
             if (isRo) { opts.view = true; }
-            var hash = Hash.getHiddenHashFromKeys(parsed.type, secret, opts);
+            var hash = Hash.getHiddenHashFromKeys(parsed.type, secret, opts, parsed.hashData.auditorKey);
```
Comment (yflory) [inline www/common/drive-ui.js:1253]: See previous comment, we shouldn't add keys to the "hidden hashes" (a.k.a. safe links).
